#!/usr/bin/env python3
"""Build `src/tests/data/inputs/windows_fixture.tsv` and the subset proteome.

The point of this script is that it is an **oracle, not an echo**: every
`expected_15mer` is computed here by slicing the raw (unpadded) sequence with
explicit bounds and explicit underscore padding, deliberately *not* by calling
`kinase_library.modules.sequences`. A fixture generated by the code under test
proves only that the code agrees with itself.

Rows cover: the p53 golden case, the N-terminus (positions 1, 3, 7), the
C-terminus (last residue and near it), an isoform-suffixed accession beside its
canonical twin, genes with several isoform records, and ordinary interior
sites. Nothing here comes from collaborator data.

It also writes `--mini-fasta`, a deterministic subset of the reference proteome
holding only the records the fixture and the tests need. That file is committed
so the test suite runs offline, in CI, and on a machine that does not have the
52 MB July-2021 UniProt download.

Deterministic: proteins are chosen by a fixed list or by a sorted scan, never
by hashing or sampling, so running it twice produces an identical file.

Usage:
    make_windows_fixture.py [out.tsv] [--fasta PATH] [--mini-fasta PATH]

The reference proteome is located as: `--fasta`, else the human proteome inside
`$KL_PROTEOME_DIR`, else the human proteome inside the legacy package.
"""
from __future__ import annotations

import argparse
import os
import re
import sys

from Bio import SeqIO

LEGACY_PROTEOME_DIR = (
    "/Users/tomer/My Drive/PhD/Thesis/Kinome/packages/py_kinase_library/"
    "src/py_kinase_library/databases/uniprot_sequences")

# Same candidate order the package uses: a dateless download first, then the
# July-2021 file that shipped with the legacy package.
HUMAN_FASTA_NAMES = ("human_uniprot_proteome_with_isoforms.fasta",
                     "human_uniprot_proteome_with_isoforms_07_2021.fasta")

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.normpath(
    os.path.join(HERE, "..", "data", "inputs", "windows_fixture.tsv"))
DEFAULT_MINI_FASTA = os.path.normpath(
    os.path.join(HERE, "..", "data", "inputs", "uniprot_test_proteome.fasta"))

ACCEPTORS = "STY"

# How many records carrying no `GN=` field to carry into the subset. The full
# human FASTA has 845 of them; they must drop out of a gene-symbol index rather
# than becoming a NaN key, and three is enough to test that.
N_RECORDS_WITHOUT_GENE = 3

# Proteins the fixture is built from, chosen for what they exercise rather than
# for their biology. P04637 (p53) carries the golden case; P28482 (ERK2) gives
# the TEY activation loop; the rest are ordinary well-known kinases and
# substrates with isoform records in this FASTA.
SEED_ACCESSIONS = ["P04637", "P28482", "P27361", "P31749", "P06239",
                   "P00533", "P42345", "Q00266", "P05412", "P01100",
                   "P38398", "Q9Y6K9", "P17252", "Q13315", "P49841",
                   "P68400", "P06400", "Q16539"]


def find_reference_proteome(explicit: str | None = None) -> str:
    """The human reference proteome: explicit, then env var, then legacy."""
    if explicit:
        return explicit
    directories = [d for d in (os.environ.get("KL_PROTEOME_DIR"),
                               LEGACY_PROTEOME_DIR) if d]
    for directory in directories:
        for name in HUMAN_FASTA_NAMES:
            candidate = os.path.join(directory, name)
            if os.path.isfile(candidate):
                return candidate
    raise FileNotFoundError(
        "no human reference proteome found. Looked for "
        f"{list(HUMAN_FASTA_NAMES)} in {directories}. "
        "Pass --fasta PATH, or set KL_PROTEOME_DIR.")


def oracle_window(raw: str, pos: int) -> str:
    """The 15-mer centred on 1-based `pos`, computed independently.

    Seven characters either side, padded with underscores where the protein
    runs out. Written to be read, not to be clever: an explicit loop over the
    fifteen offsets, so it shares no code path with the module under test.
    """
    out = []
    for offset in range(-7, 8):
        index = pos + offset          # 1-based
        out.append(raw[index - 1] if 1 <= index <= len(raw) else "_")
    return "".join(out)


def _header_fields(header: str) -> tuple[str, str | None]:
    """`(accession, gene_or_None)` from a raw FASTA header line."""
    identifier = header[1:].split(None, 1)[0]
    parts = identifier.split("|")
    accession = parts[1] if len(parts) > 1 else identifier
    gene = re.search(r"GN=([^\s]+)", header)
    return accession, (gene.group(1) if gene else None)


def write_mini_fasta(source: str, out_path: str, genes: set[str]) -> dict[str, int]:
    """Copy the records the tests need, verbatim and in original file order.

    Kept: every record whose base accession is a seed, every record sharing a
    seed's `GN=` symbol (which is what pulls in the TrEMBL entries a
    gene-symbol collision test needs), and the first few records carrying no
    `GN=` at all. Records are copied as raw text rather than re-serialised, so
    the subset's headers and line wrapping are byte-identical to the source.
    """
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    wanted_bases = set(SEED_ACCESSIONS)
    counts = {"seed": 0, "gene": 0, "no_gene": 0, "swissprot": 0, "trembl": 0}

    block: list[str] = []
    keep = False
    no_gene_kept = 0

    def decide(header: str) -> bool:
        nonlocal no_gene_kept
        accession, gene = _header_fields(header)
        if accession.split("-")[0] in wanted_bases:
            counts["seed"] += 1
            return True
        if gene is None:
            if no_gene_kept < N_RECORDS_WITHOUT_GENE:
                no_gene_kept += 1
                counts["no_gene"] += 1
                return True
            return False
        if gene in genes:
            counts["gene"] += 1
            return True
        return False

    with open(source) as handle, open(out_path, "w") as out:
        for line in handle:
            if line.startswith(">"):
                if keep:
                    out.writelines(block)
                block = [line]
                keep = decide(line)
                if keep:
                    counts["swissprot" if line.startswith(">sp|") else "trembl"] += 1
            elif keep:
                block.append(line)
        if keep:
            out.writelines(block)
    return counts


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="make_windows_fixture.py",
        description="Regenerate the window fixture and the subset proteome.")
    parser.add_argument("out", nargs="?", default=DEFAULT_OUT,
                        help="fixture TSV to write")
    parser.add_argument("--fasta", default=None,
                        help="reference proteome (default: KL_PROTEOME_DIR, "
                             "else the legacy package)")
    parser.add_argument("--mini-fasta", default=DEFAULT_MINI_FASTA,
                        help="subset proteome to write for the test suite")
    args = parser.parse_args(argv)

    fasta = find_reference_proteome(args.fasta)
    out_path = args.out
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)

    wanted = set(SEED_ACCESSIONS)
    canonical: dict[str, tuple[str, str, str]] = {}   # acc -> (name, gene, seq)
    isoforms: dict[str, tuple[str, str, str]] = {}    # acc-N -> (name, gene, seq)

    with open(fasta) as handle:
        for record in SeqIO.parse(handle, "fasta"):
            accession = record.id.split("|")[1]
            base = accession.split("-")[0]
            if base not in wanted:
                continue
            gene = re.search(r"GN=([^\s]+)", record.description)
            entry = (record.id, gene.group(1) if gene else "", str(record.seq))
            if "-" in accession:
                isoforms.setdefault(accession, entry)
            else:
                canonical[accession] = entry

    rows: list[tuple[str, str, str, str, str, str]] = []

    def add(acc: str, pos: int, site: str, kind: str) -> None:
        name, gene, raw = (canonical.get(acc) or isoforms[acc])
        rows.append((acc, gene, str(pos), site, oracle_window(raw, pos), kind))

    def first_acceptor(raw: str, lo: int, hi: int, step: int = 1):
        """Lowest 1-based position in [lo, hi] whose residue is S/T/Y."""
        for pos in range(lo, hi + 1, step):
            if 1 <= pos <= len(raw) and raw[pos - 1] in ACCEPTORS:
                return pos
        return None

    # --- the golden case, stated explicitly ---
    add("P04637", 15, "S15", "golden_p53_ATM_site")
    add("P04637", 33, "S33", "interior")

    # --- N-terminus: the first acceptor at or below position 7 ---
    for acc in SEED_ACCESSIONS:
        if acc not in canonical:
            continue
        raw = canonical[acc][2]
        pos = first_acceptor(raw, 1, 7)
        if pos is not None:
            add(acc, pos, f"{raw[pos - 1]}{pos}", "n_terminus")

    # --- C-terminus: the highest acceptor within 7 of the end ---
    for acc in SEED_ACCESSIONS:
        if acc not in canonical:
            continue
        raw = canonical[acc][2]
        for pos in range(len(raw), max(len(raw) - 7, 0), -1):
            if raw[pos - 1] in ACCEPTORS:
                add(acc, pos, f"{raw[pos - 1]}{pos}", "c_terminus")
                break

    # --- an isoform beside its canonical twin, at a position where they differ ---
    for iso_acc in sorted(isoforms):
        base = iso_acc.split("-")[0]
        if base not in canonical:
            continue
        iso_raw, can_raw = isoforms[iso_acc][2], canonical[base][2]
        upper = min(len(iso_raw), len(can_raw))
        # The position must be a phosphoacceptor in BOTH sequences, and the two
        # windows must differ. Requiring it only of the isoform produced a
        # canonical twin centred on alanine -- not a phosphosite at all, and a
        # row no window-building test could legitimately assert against.
        pos = next(
            (p for p in range(8, upper - 7)
             if iso_raw[p - 1] in ACCEPTORS
             and can_raw[p - 1] in ACCEPTORS
             and oracle_window(iso_raw, p) != oracle_window(can_raw, p)),
            None)
        if pos is None:
            continue
        add(iso_acc, pos, f"{iso_raw[pos - 1]}{pos}", "isoform")
        add(base, pos, f"{can_raw[pos - 1]}{pos}", "isoform_canonical_twin")
        if sum(1 for r in rows if r[5] == "isoform") >= 4:
            break

    # --- ordinary interior sites: several per protein, at spaced-out offsets,
    # --- so the fixture is wide enough to catch a systematic off-by-one
    for acc in SEED_ACCESSIONS:
        if acc not in canonical:
            continue
        raw = canonical[acc][2]
        for start in (60, 120, 200, 300):
            if start > len(raw) - 20:
                break
            pos = first_acceptor(raw, start, min(start + 40, len(raw) - 8))
            if pos is not None:
                add(acc, pos, f"{raw[pos - 1]}{pos}", "interior")

    header = "acc\tgene\tpos\tsite_str\texpected_15mer\tkind\n"
    with open(out_path, "w") as fh:
        fh.write(header)
        for row in rows:
            fh.write("\t".join(row) + "\n")

    print(f"proteome : {fasta}")
    print(f"wrote {len(rows)} rows -> {out_path}")
    kinds: dict[str, int] = {}
    for row in rows:
        kinds[row[5]] = kinds.get(row[5], 0) + 1
    for kind, count in sorted(kinds.items()):
        print(f"  {count:>3}  {kind}")

    genes = {gene for _, gene, _ in canonical.values() if gene}
    counts = write_mini_fasta(fasta, args.mini_fasta, genes)
    total = counts["swissprot"] + counts["trembl"]
    size = os.path.getsize(args.mini_fasta)
    print(f"\nwrote {total} records ({size} bytes) -> {args.mini_fasta}")
    print(f"  {counts['seed']:>3}  seed accessions (canonical + isoforms)")
    print(f"  {counts['gene']:>3}  sharing a seed gene symbol")
    print(f"  {counts['no_gene']:>3}  carrying no GN= field")
    print(f"  {counts['swissprot']:>3}  sp|   {counts['trembl']:>3}  tr|")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
